language: ruby
rvm: 2.6
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- gem install bundler
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  app: own-knowledge-base
  api_key: 00ee9806-dec6-4b4b-b945-b6fa71fea896
