development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: 'own-knowledge-base_dev'
  pool: 5
  username: 'own-knowledge-base'
  port: 5432

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: 'own-knowledge-base_test'
  pool: 5
  username: 'own-knowledge-base'
  port: 5432
