# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f887a25f62d32025331192de5c75e550f7841a3aaf372f4d8841224ee9401f26ba2966e41acade1e9b52aaa8333d7c905eb95cbd90a6a92f47bfadd84126177

test:
  secret_key_base: be36fdcca2e4c7a8da45809e2a0929ad09707b7bd2fc9a02a8432ea5318739e8743f5ab84b599041bd3b424855da4af207be297a3379273e6a0fcd8f3bf6bc90

circleci:
  secret_key_base: be36fdcca2e4c7a8da45809e2a0929ad09707b7bd2fc9a02a8432ea5318739e8743f5ab84b599041bd3b424855da4af207be297a3379273e6a0fcd8f3bf6bc90

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
